- name: Check host connection and configure servers
  hosts: servers
  become: yes
  gather_facts: false
  vars_files:
    - secrets1.yaml
    - secrets2.yaml

  tasks:
    - name: Set sudo password dynamically
      set_fact:
        ansible_become_password: "{{ ansible_become_password if ansible_become_password is defined else ansible_become_password_alt }}"

    - name: Ping hosts
      ansible.builtin.ping:

    - name: Ensure the sudo logfile is set
      lineinfile:
        path: /etc/sudoers
        regexp: '^Defaults\s+logfile'
        line: 'Defaults        logfile="/var/log/sudo"'
        state: present
        validate: '/usr/sbin/visudo -cf %s'

    - name: Grant passwordless sudo to ubuntu user
      lineinfile:
        path: /etc/sudoers
        regexp: '^ubuntu\s+ALL=\(ALL\)\s+NOPASSWD:ALL'
        line: 'ubuntu  ALL=(ALL) NOPASSWD:ALL'
        state: present
        validate: '/usr/sbin/visudo -cf %s'
